### ISSUE TITLE
defualt.yaml moved?

### ISSUE THREAD

**Issue by Mjvolk3** [DennisGankin/species-aware-DNA-LM#5]
The only `default.yaml` I can find lives in `configs/trainer/default.yaml`. I don't think `test.yaml` is reading this properly. There should be a `callbacks` dir.

From `test.yaml`,

```yaml
defaults:
  - _self_
  - datamodule: roll_mask_test.yaml
  - model: motif_s4_resnet.yaml
  - callbacks: default.yaml
```

```bash
michaelvolk@M1-MV species-aware-DNA-LM % python test.py experiment=test_species_in_scer --multirun                                              14:25
In 'test.yaml': Could not find 'callbacks/default.yaml'

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///Users/michaelvolk/Documents/projects/species-aware-DNA-LM/configs
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
